---
- hosts: api_gateway
  roles:
    - { role: docker, tags: docker }
    - { role: api_gateway, tags: api_gateway }
  vars:
    node: 1
    gateway_port: 9500
  become: yes
  tags:
    - deploy_api_gateway
    - deploy_api_gateway_node_1

- hosts: api_gateway
  roles:
    - { role: docker, tags: docker }
    - { role: api_gateway, tags: api_gateway }
  vars:
    node: 2
    gateway_port: 9501
  become: yes
  tags:
    - deploy_api_gateway
    - deploy_api_gateway_node_2
