---
- hosts: api_gateway
  roles:
    - { role: docker, tags: docker }
    - { role: api_gateway, tags: api_gateway }
  vars:
    node: 1
    port: 9000
  become: yes
  tags: deploy_api_gateway

- hosts: api_gateway
  roles:
    - { role: docker, tags: docker }
    - { role: api_gateway, tags: api_gateway }
  vars:
    node: 2
    port: 9001
  become: yes
  tags: deploy_api_gateway
