---
- hosts: api_gateway_1
  roles:
    - { role: docker, tags: docker }
    - { role: api_gateway, tags: api_gateway }
  become: yes
  tags: deploy_api_gateway

- hosts: api_gateway_2
  roles:
    - { role: docker, tags: docker }
    - { role: api_gateway, tags: api_gateway }
  become: yes
  tags: deploy_api_gateway
