---
- name: Pull docker image
  command: "docker pull {{ image_name }}"
  notify:
    - Systemctl Daemon Reload
    - Systemctl Enable Service
    - Restart Service

- name: Copy config file
  template:
    src: "api_gateway.json"
    dest: "{{ user_dir }}/api_gateway.json"
    backup: yes

- name: Create Krakend Service
  template:
    src: "api_gateway.j2"
    dest: "/etc/systemd/system/api_gateway.service"
    backup: yes
  notify:
    - Systemctl Daemon Reload
    - Systemctl Enable Service
    - Restart Service
