---
- name: Pull docker image
  command: "docker pull {{ image_name }}"
  notify:
    - Systemctl Daemon Reload
    - Systemctl Enable Service
    - Restart Service

- name: Create api gateway directory if it does not exist
  file:
    path: "{{ root_dir }}"
    state: directory
    mode: '0755'

- name: Copy config file
  template:
    src: "api_gateway.json.j2"
    dest: "{{ root_dir }}/{{ config_file }}"
    backup: yes

- name: Create Krakend Service
  template:
    src: "api_gateway.j2"
    dest: "/etc/systemd/system/api_gateway_node_{{ node }}.service"
    backup: yes
  notify:
    - Systemctl Daemon Reload
    - Systemctl Enable Service
    - Restart Service
