---
- name: Pull docker image
  command: "docker pull {{ image_name }}"

- name: Create api gateway directory if it does not exist
  file:
    path: "{{ root_dir }}"
    state: directory
    mode: '0755'

- name: Copy config file
  template:
    src: "api_gateway.json"
    dest: "{{ root_dir }}/{{ config_file }}"

- name: Create Krakend Service
  template:
    src: "api_gateway.j2"
    dest: "/etc/systemd/system/api_gateway_node_{{ node }}.service"

- name: Systemctl Daemon Reload
  shell: systemctl daemon-reload

- name: Systemctl Enable Service
  shell: "systemctl enable api_gateway_node_{{ node }}"

- name: Restart Service
  service:
    name: "api_gateway_node_{{ node }}"
    state: restarted
