---
- name: Pull docker image
  command: "docker pull {{ image_name }}"
  notify:
    - Systemctl Daemon Reload
    - Systemctl Enable Service
    - Restart Service

- name: Copy config file
  template:
    src: "krakend.json"
    dest: "{{ user_dir }}/krakend.json"
    backup: yes

- name: Create Krakend Service
  template:
    src: "krakend_service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    backup: yes
  notify:
    - Systemctl Daemon Reload
    - Systemctl Enable Service
    - Restart Service
