name: Deploy API Gateway

on: [ push ]

jobs:
  deploy:
    name: Deploy api gateway service
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to api gateway instances using ansible
        run: |
          cd ansible
          export ANSIBLE_ROLES_PATH=./roles
          /home/ubuntu/.local/bin/ansible-playbook playbooks/api_gateway.yml -i inventory/qa.ini